version: "3"

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - database
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html

  database:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password123

  php:
    build: docker
    depends_on:
      - database
    volumes:
      - ./:/usr/share/nginx/html

volumes:
  db_data: {}